before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y  wget unzip librdkafka-dev 
language: c
compiler:
    - clang
    - gcc
dist: trusty
env:
  - NGX_JSON_VAR_MODULE=--add-module=$TRAVIS_BUILD_DIR
  - NGX_JSON_VAR_MODULE=--add-dynamic-module=$TRAVIS_BUILD_DIR
script: ./travis_build.sh $NGX_JSON_VAR_MODULE
notifications:
  email:
    recipients:
      - eran.kornblau@kaltura.com
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
